# version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 20011976qQ
      POSTGRES_DB: postgresdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - default

  # redis:
  #   image: redis:7

  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./src:/app
      - app-data:/app/data
    ports:
      - "8000:8000"
    depends_on:
      - db
      # - redis
    env_file:
      - .env

  # celery:
  #   build: .
  #   command: celery -A app.celery:celery_app worker --loglevel=info
  #   volumes:
  #     - ./src:/app
  #   depends_on:
  #     - db
  #     # - redis
  #   env_file:
  #     - .env

volumes:
  postgres_data:
